export class userPrivileges
{
  viewAllJob:boolean;
  inviteUser:boolean;
  assignRole:boolean;
  assignPrivilege:boolean;
  createNewRole:boolean;
  postJob:boolean;
  assignJob:boolean;
  viewJob:boolean;
  editJob:boolean;
  approveJob:boolean;
  uploadResume:boolean;
  viewResume:boolean;
  downloadResume:boolean;
  shortlistResume:boolean;
  discardResume:boolean;
  downloadQuestion:boolean;
  uploadQuestion:boolean;
  viewQuestion:boolean;
  referJob:boolean;
  adminDashboard:boolean;
  ManagerDashboard:boolean;
  recruiterDashboard:boolean;
  recHeadDashboard:boolean;
  rejectJob:boolean;
  onHoldJob:boolean;
  closeJob:boolean;
}
