// Generated by https://quicktype.io

export class ReferedLevel {
    candidateName: string;
    emailId:       string;
    hireRequest:   HireRequest;
    tenant:        Tenant;
    user:          User;
    constructor(){
        this.tenant= new Tenant();
        this.hireRequest=new HireRequest();
        this.user=new User();
    }
}

export class HireRequest {
    hirerequestId: string;
}

export class Tenant {
    tenantId: string;
}

export class User {
    userId: string;
}
